### ISSUE TITLE
HOW TO INSTALL TE PLUGIN?

### ISSUE THREAD

**Issue by Lorusso3** [Azzinoth/UnityPointCloudPlugin#2]
CAN YOU HELP ME WITH THE IMPORTATION IN UNITY?

**Comment by Azzinoth** [comment]
Hello! This repository contains only part of the code for the VR-Point-Cloud-Editor. To use the VR cleaner, please refer to the full application [here](https://github.com/ahstevens/VR-Point-Cloud-Editor) and follow these [instructions](https://ccom.unh.edu/vislab/tools/point_cloud_editor/#instructions).

**Comment by Lorusso3** [comment]
Thank you for your reply. I would only need the Unity Plugin to be able to import the point cloud and use it in AR applications. Could you tell me how to proceed? Unfortunately I have little experience in coding :(

**Comment by Azzinoth** [comment]
> Thank you for your reply. I would only need the Unity Plugin to be able to import the point cloud and use it in AR applications. Could you tell me how to proceed? Unfortunately I have little experience in coding :(

Unfortunately, code in this repository is only for a DLL part of the full application, which makes it challenging to use independently, especially with little experience in coding. This library was not designed to be an easy plug-and-play solution for other projects. 
If your intention is just to clean point clouds and not to use the DLL as part of your application for AR, then I would strongly recommend using the complete application.

You can find the full VR-Point-Cloud-Editor application at: 
https://ccom.unh.edu/vislab/tools/point_cloud_editor/
Or 
https://github.com/ahstevens/VR-Point-Cloud-Editor
